version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "/tests/trac/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/tests/openproject/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/tests/trac/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5
