#!/bin/bash

# Copyright (c) 2022 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
# https://www.gnu.org/licenses/agpl-3.0.html

set -ex

BASE_DIR=$(dirname $0)

# default login is administrator/root
IP_ADDR=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bugtracker_kiwitcms_org)

MANTIS_URL="https://${IP_ADDR}:8443/mantisbt"
MANTIS_API_TOKEN=$(robot --variable IP_ADDR:${IP_ADDR} --quiet --log NONE --report NONE --output NONE ${BASE_DIR}/initialize.robot)

echo "export MANTIS_API_TOKEN=${MANTIS_API_TOKEN}" > /tmp/env
echo "export MANTIS_URL=${MANTIS_URL}" >> /tmp/env
